### ISSUE TITLE
Prebuilt Visual Teensy 1.0.0.0 fails to start when deserializing additionalFiles

### ISSUE THREAD

**Issue by AmadeusW** [luni64/VisualTeensy#49] opened 2021-05-26 06:25 UTC
After downloading and unzipping [Visual Teensy 1.0.0.0 from GitHub's tags page](https://github.com/luni64/VisualTeensy/releases/tag/v1.0.0.0), program crashes on startup with error in deserializing `additionalFiles`
![image](https://user-images.githubusercontent.com/1673956/119611390-7d0f1900-bdaf-11eb-8e02-be808357eb36.png)

This does not repro when I build locally.

I thought there is a difference in `.config` files, but neither downloaded nor built `VisualTeensy.exe.config` contains the `additionalFiles` entry.

**Comment by luni64** [comment] 2021-05-26 07:18
Looks like there is a bug when upgrading an existing user config file.  Can you try to delete your user config file? It lives here in  AppData\Local\lunOptics.  (here: C:\Users\lutz\AppData\Local\lunOptics). Best to delete the whole contents of the folder.

**Comment by AmadeusW** [comment] 2021-05-28 06:02
This worked. I removed (renamed for backup) the lunOptics directory and was able to start from scratch and without issues.

**Comment by luni64** [comment] 2021-05-28 06:18
Thanks a lot for testing this. I had a brief look at the code yesterday and it looks like the setup file has problems with initializing the List<string> I use for the "additional files". I'll check if the problem is on my side and look for a fix.

**Comment by luni64** [comment] 2021-08-23 16:03
fixed in v1.2.0

**Closed by luni64** 2021-08-23 16:03 UTC
